gallery/api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'comments', views.CommentViewSet)

app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('like/<int:pk>/', views.LikeView.as_view(), name='like'),
    path('dizlike/<int:pk>/', views.DizlikeView.as_view(), name='dizlike'),
]

gallery/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'

urlpatterns = [
    path('', views.PhotosView.as_view(), name='index'),
    path('photo/<int:pk>/', views.PhotoDetail.as_view(), name='photo_detail'),
    path('photo/add/', views.PhotoCreateView.as_view(), name='photo_create'),
    path('photo/edit/<int:pk>', views.PhotoUpdateView.as_view(), name='photo_update'),
    path('photo/delete/<int:pk>', views.PhotoDeleteView.as_view(), name='photo_delete'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

gallery/api/models.py
from django.db import models

# Create your models here.

gallery/webapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Album(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name='Название')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    author = models.ForeignKey(User, related_name='albums', on_delete=models.CASCADE, verbose_name='Автор')
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_private = models.BooleanField(verbose_name='приватный', default=False)

    def __str__(self):
        return self.name


class Photo(models.Model):
    album = models.ForeignKey('webapp.Album', related_name='photos', null=True, blank=True, on_delete=models.CASCADE,
                              verbose_name='Альбом')
    photo = models.ImageField(upload_to='photos', verbose_name='Фото')
    note = models.CharField(max_length=100, verbose_name='Подпись')
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    author = models.ForeignKey(User, related_name='photos', on_delete=models.CASCADE, verbose_name='Автор')
    likes = models.IntegerField(default=0, verbose_name='Лайки')
    is_private = models.BooleanField(verbose_name='приватный', default=False)

    def __str__(self):
        return self.note


class Like(models.Model):
    author = models.ForeignKey(User, related_name='user_likes', on_delete=models.CASCADE, verbose_name='Автор')
    photo = models.ForeignKey('webapp.Photo', related_name='photo_likes', on_delete=models.CASCADE, verbose_name='Фото')

    class Meta:
        unique_together = ('author', 'photo')


class Comment(models.Model):
    text = models.TextField(max_length=500, verbose_name='Текст')
    photo = models.ForeignKey('webapp.Photo', related_name='photo_comments', on_delete=models.CASCADE,
                              verbose_name='Фото')
    author = models.ForeignKey(User, related_name='author_comments', on_delete=models.CASCADE, verbose_name='Автор')
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return self.text

gallery/webapp/forms.py
from django import forms
from webapp.models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        exclude = ['create_at', 'author', 'likes']

gallery/api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from webapp.models import Comment, Photo, Like
from api.serializers import CommentSerializer


class CommentViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


class LikeView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        photo_pk = kwargs.get('pk')
        try:
            like = Like()
            like.author_id = self.request.user.pk
            like.photo_id = photo_pk
            like.save()
        except:
            return Response({'status': 'Лайк уже есть.'})

        photo = Photo.objects.get(pk=photo_pk)
        photo.likes += 1
        photo.save()
        return Response({'id': photo.pk, 'rating': photo.likes, 'status': 'ok'})


class DizlikeView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        photo_pk = kwargs.get('pk')

        like = Like.objects.filter(author=request.user.pk)
        if like:
            like.delete()
            photo = Photo.objects.get(pk=photo_pk)
            photo.likes -= 1
            photo.save()
            return Response({'id': photo.pk, 'rating': photo.likes, 'status': 'ok'})
        return Response({'status': 'error'})

gallery/webapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotAllowed
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import PhotoForm
from webapp.models import Photo


@ensure_csrf_cookie
def get_token_view(request, *args, **kwargs):
    if request.method == 'GET':
        return HttpResponse()
    return HttpResponseNotAllowed('Only GET request are allowed')


class PhotosView(ListView):
    template_name = 'index.html'
    model = Photo
    context_object_name = 'photos'


class PhotoDetail(DetailView):
    template_name = 'photo_detail.html'
    model = Photo
    context_object_name = 'photo'


class PhotoCreateView(LoginRequiredMixin, CreateView):
    template_name = 'photo_create.html'
    model = Photo
    form_class = PhotoForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:index')


class PhotoUpdateView(UserPassesTestMixin, UpdateView):
    model = Photo
    class_form = PhotoForm
    template_name = 'photo_update.html'
    context_object_name = 'photo'
    fields = ['photo', 'note']

    def test_func(self):
        photo_pk = self.kwargs.get('pk')
        photo = Photo.objects.get(pk=photo_pk)
        return self.request.user == photo.author or self.request.user.has_perm('webapp.change_photo')

    def get_success_url(self):
        return reverse('webapp:index')


class PhotoDeleteView(UserPassesTestMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        photo_pk = self.kwargs.get('pk')
        photo = Photo.objects.get(pk=photo_pk)
        return self.request.user == photo.author or self.request.user.has_perm('webapp.delete_photo')


def login_view(request):
    context = {}
    next_page = request.GET.get('next')
    url = request.session.setdefault('url', next_page)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if url:
                return redirect(url)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')

gallery/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Галерея</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'webapp:index' %}">Галерея</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'webapp:index' %}">На главную</a>
                <a class="nav-item nav-link" href="{% url 'webapp:photo_create' %}">Добавить фото</a>
            </div>
        </div>
    </div>
    <div class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="">
                Привет, {{ user.username }}</a>
            <a class="nav-item nav-link" href="{% url 'webapp:logout' %}">Выйти</a>
        {% else %}
            <a class="nav-item nav-link" href="{% url 'webapp:login' %}">Войти</a>
        {% endif %}
    </div>
</nav>
<div class="container">
    <br>
    {% block body %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"
        integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

gallery/webapp/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block body %}
    {% for photo in photos %}
        <div class="card col-6 mb-5">
        <h5 class="card-title">Название альбома: {{ photo.name }}</h5>
            <img src="{{ photo.photo.url }}" class="card-img-top" alt="{{ photo.note }}">
            <div class="card-body">
                <h5 class="card-title">{{ photo.note }}</h5>
                <p class="card-text">Рейтинг: <span id="likes_{{ photo.id }}">{{ photo.likes }}</span></p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><small
                        class="text-muted">Добавлено пользователем {{ photo.author }}</small>
                </li>
                <li class="list-group-item"><small
                        class="text-muted">Дата добавления: {{ photo.create_at|date:'d.m.Y H:i:s' }}</small>
                </li>
            </ul>
            <div class="card-body">
                <a href="{% url 'webapp:photo_detail' photo.pk %}" class="btn btn-success">Просмотр</a>
                {% if perms.webapp.change_photo or request.user.id == photo.author.id %}
                    <a href="{% url 'webapp:photo_update' photo.pk %}" class="btn btn-primary">Редактировать</a>
                    <form action="{% url 'webapp:photo_delete' photo.pk %}" method="post" class="d-inline-block">
                        {% csrf_token %}
                        <input type="submit" value="Удалить" class="btn btn-danger">
                    </form>
                {% endif %}
                {% if user.is_authenticated %}
                    <button class="btn btn-info" onclick="like({{ photo.pk }})" id="like_{{ photo.pk }}">Лайк</button>
                    <button class="btn btn-info" onclick="dizlike({{ photo.pk }})" id="dizlike_{{ photo.pk }}">Дизлайк</button>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

gallery/webapp/templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% load static %}
</head>
<body class="text-center">

<form class="form-signin" action="{% url 'webapp:login' %}" method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Вход</h1>
    {% if has_error %}
        <div class="alert alert-danger" role="alert">
            Неверный логин или пароль
        </div>
    {% endif %}
    <label for="username" class="sr-only">Username</label>
    <input type="text" id="username" class="form-control" placeholder="Логин" required autofocus
           name="username">
    <label for="password" class="sr-only">Password</label>
    <input type="password" id="password" class="form-control" placeholder="Пароль" required name="password">
    <button class="btn btn-lg btn-primary btn-block mb-3" type="submit">войти</button>
    <a href="{% url 'webapp:index' %}">На главную</a>
</form>
</body>
</html>

gallery/webapp/templates/partial/form.html
{% load widget_tweaks %}
{% csrf_token %}
{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}
{% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}" class="mr-3">{{ field.label }}</label>
        {% if field|field_type == 'imagefield' %}
            {{ field }}
        {% else %}
            {{ field|add_class:"form-control" }}
        {% endif %}
        {% for error in field.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}
<input type="submit" value="{{ button_text }}" class="btn btn-success">
<button onclick="history.back();" class="btn btn-primary">Отмена</button>

gallery/webapp/templates/photo_create.html
{% extends 'base.html' %}

{#{% block title %}Добавить фото{% endblock %}#}

{% block body %}
    <h1 class="text-center mb-5">Добавить новое фото</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Создать' %}
    </form>
{% endblock %}

gallery/webapp/templates/photo_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ photo.note }}
{% endblock %}

{% block body %}
    <div class="card col-6 mb-5">
        <img src="{{ photo.photo.url }}" class="card-img-top" alt="{{ photo.note }}">
        <div class="card-body">
            <h5 class="card-title">{{ photo.note }}</h5>
            <p class="card-text">Лайки: {{ photo.likes }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><small
                    class="text-muted">Добавлено: {{ photo.create_at|date:'d.m.Y H:i:s' }}</small></li>
            <li class="list-group-item"><small
                    class="text-muted">Название альбома: {{ photo.album}}</small></li>
            <li class="list-group-item"><small
                    class="text-muted">Описание: {{ photo.description }}</small></li>
        </ul>
        <div class="card-body">
        </div>
    </div>

    {% if user.is_authenticated %}
        <h3>Добавить комментарий</h3>
        <div class="form-group col-8 d-inline-block">
            <label for="commentText">Комментарий</label>
            <input value="" type="text" class="form-control" id="commentText" placeholder="Текст комментария">
        </div>
        <button type="button" class="btn btn-success col-2" onclick="addComment({{ photo.pk }})">Добавить</button>
    {% endif %}


    <div class="mt-5" id="comments">
        <h3>Комментарии:</h3>
        {% for comment in photo.photo_comments.all %}
            <div class="card mb-2" id="comment_{{ comment.pk }}">
                <div class="card-header text-danger">
                    Комментрий от {{ comment.author }}
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>{{ comment.text }}</p>
                        <footer class="blockquote-footer">Дата
                            добавления: {{ comment.create_at|date:'Y-m-d H:i:s' }}</footer>
                    </blockquote>
                </div>
                {% if request.user.id == comment.author.id or perms.webapp.delete_comment %}
                    <button class="btn btn-danger" onclick="deleteComment({{ comment.pk }})" id="deleteComment">Удалить комментарий</button>
                {% endif %}

            </div>

        {% empty %}
            <p>Нет комментариев</p>
        {% endfor %}
    </div>



{% endblock %}

gallery/webapp/templates/photo_update.html
{% extends 'base.html' %}

{% block title %}Редактировать фото{% endblock %}

{% block body %}
    <h1 class="text-center mb-5">Редактировать фото</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Обновить' %}
    </form>
{% endblock %}